// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBWoCKa3u9fF43p1woUqaHfa5tIrqSUsA',
    appId: '1:1027577779488:android:b1b3e6b624b16b3e72f345',
    messagingSenderId: '1027577779488',
    projectId: 'remmikub-school-project',
    databaseURL: 'https://remmikub-school-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'remmikub-school-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaEL_EArw8oUC0P9L2OawhR8Aiy8e670Q',
    appId: '1:1027577779488:ios:c2e87385b2ed196472f345',
    messagingSenderId: '1027577779488',
    projectId: 'remmikub-school-project',
    databaseURL: 'https://remmikub-school-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'remmikub-school-project.firebasestorage.app',
    androidClientId: '1027577779488-sh82aqr951kbvdl1vqlpn92lg0eocp7m.apps.googleusercontent.com',
    iosClientId: '1027577779488-9epehflb6celoqiipjvcugoehqi0e9ne.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCN7OfWP7WhtJSi1LCfJL824W_iHaGb_8',
    appId: '1:1027577779488:web:c23148d07890c93772f345',
    messagingSenderId: '1027577779488',
    projectId: 'remmikub-school-project',
    authDomain: 'remmikub-school-project.firebaseapp.com',
    databaseURL: 'https://remmikub-school-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'remmikub-school-project.firebasestorage.app',
  );

}